#source: https://docs.ansible.com/ansible/2.6/modules/vmware_guest_powerstate_module.html
#Playbook to be launched from AWX or Ansible Tower.
- name:  VC Modify Memory and CPU
  hosts: all
  gather_facts: false
  tasks:
      - name: Modify Memory and CPU
        vmware_guest_powerstate:
          #hostname: '{{ vcenter_hostname }}'
          #username: '{{ vcenter_username }}'
          #password: '{{ vcenter_password }}'
          #validate_certs: no
          #folder:         
          name: '{{ vm_name }}'
          hardware:
            memory_mb: "{{ memory }}"
            num_cpus: "{{ cpus }}"
            num_cpu_cores_per_socket: "{{ cores }}"
            #scsi: paravirtual
            #memory_reservation: 512
            #memory_reservation_lock: True
            #mem_limit: 8096
            #mem_reservation: 4096
            #cpu_limit: 8096
            #cpu_reservation: 4096
            #max_connections: 5
            hotadd_cpu: True
            hotremove_cpu: True
            hotadd_memory: True
        delegate_to: localhost
        register: deploy
