#source: https://docs.ansible.com/ansible/2.6/modules/vmware_guest_powerstate_module.html
#Playbook to be launched from AWX or Ansible Tower.
- name:  VC PowerOn or PowerOff VM
  hosts: all
  gather_facts: false
  tasks:
      - name: PowerOn or PowerOff VM
        vmware_guest_powerstate:
          name: '{{ vm_name }}'
          state: '{{ power_state }}' #powered-off or powered-on or reboot-guest or restarted or shutdown-guest or suspended
        delegate_to: localhost
        register: deploy
